// This file will be generated by Supabase CLI
// Run: npm run db:generate

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export interface Database {
  public: {
    Tables: {
      organizations: {
        Row: {
          id: string
          name: string
          slug: string
          domain: string | null
          plan: 'FREE' | 'PRO' | 'BUSINESS' | 'ENTERPRISE'
          seats: number
          seats_used: number
          billing_email: string
          stripe_customer_id: string | null
          stripe_subscription_id: string | null
          settings: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          name: string
          slug: string
          domain?: string | null
          plan?: 'FREE' | 'PRO' | 'BUSINESS' | 'ENTERPRISE'
          seats?: number
          seats_used?: number
          billing_email: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          name?: string
          slug?: string
          domain?: string | null
          plan?: 'FREE' | 'PRO' | 'BUSINESS' | 'ENTERPRISE'
          seats?: number
          seats_used?: number
          billing_email?: string
          stripe_customer_id?: string | null
          stripe_subscription_id?: string | null
          settings?: Json
          created_at?: string
          updated_at?: string
        }
      }
      users: {
        Row: {
          id: string
          email: string
          name: string | null
          avatar_url: string | null
          two_factor_enabled: boolean
          two_factor_secret: string | null
          public_key: string | null
          preferences: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id: string
          email: string
          name?: string | null
          avatar_url?: string | null
          two_factor_enabled?: boolean
          two_factor_secret?: string | null
          public_key?: string | null
          preferences?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          email?: string
          name?: string | null
          avatar_url?: string | null
          two_factor_enabled?: boolean
          two_factor_secret?: string | null
          public_key?: string | null
          preferences?: Json
          created_at?: string
          updated_at?: string
        }
      }
      organization_members: {
        Row: {
          id: string
          organization_id: string
          user_id: string
          role: 'OWNER' | 'ADMIN' | 'MEMBER'
          joined_at: string
        }
        Insert: {
          id?: string
          organization_id: string
          user_id: string
          role?: 'OWNER' | 'ADMIN' | 'MEMBER'
          joined_at?: string
        }
        Update: {
          id?: string
          organization_id?: string
          user_id?: string
          role?: 'OWNER' | 'ADMIN' | 'MEMBER'
          joined_at?: string
        }
      }
      email_accounts: {
        Row: {
          id: string
          user_id: string
          grant_id: string
          email: string
          provider: 'GOOGLE' | 'MICROSOFT' | 'IMAP' | 'EXCHANGE' | 'ICLOUD' | 'YAHOO'
          name: string | null
          is_primary: boolean
          metadata: Json
          created_at: string
          updated_at: string
        }
        Insert: {
          id?: string
          user_id: string
          grant_id: string
          email: string
          provider: 'GOOGLE' | 'MICROSOFT' | 'IMAP' | 'EXCHANGE' | 'ICLOUD' | 'YAHOO'
          name?: string | null
          is_primary?: boolean
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
        Update: {
          id?: string
          user_id?: string
          grant_id?: string
          email?: string
          provider?: 'GOOGLE' | 'MICROSOFT' | 'IMAP' | 'EXCHANGE' | 'ICLOUD' | 'YAHOO'
          name?: string | null
          is_primary?: boolean
          metadata?: Json
          created_at?: string
          updated_at?: string
        }
      }
      usage_tracking: {
        Row: {
          id: string
          organization_id: string | null
          user_id: string
          feature: 'ai_remix' | 'ai_dictate' | 'voice_message' | 'sms' | 'calendar_event' | 'smart_compose'
          count: number
          metadata: Json | null
          timestamp: string
        }
        Insert: {
          id?: string
          organization_id?: string | null
          user_id: string
          feature: 'ai_remix' | 'ai_dictate' | 'voice_message' | 'sms' | 'calendar_event' | 'smart_compose'
          count?: number
          metadata?: Json | null
          timestamp?: string
        }
        Update: {
          id?: string
          organization_id?: string | null
          user_id?: string
          feature?: 'ai_remix' | 'ai_dictate' | 'voice_message' | 'sms' | 'calendar_event' | 'smart_compose'
          count?: number
          metadata?: Json | null
          timestamp?: string
        }
      }
    }
    Views: {}
    Functions: {}
    Enums: {
      plan_type: 'FREE' | 'PRO' | 'BUSINESS' | 'ENTERPRISE'
      role_type: 'OWNER' | 'ADMIN' | 'MEMBER'
      provider_type: 'GOOGLE' | 'MICROSOFT' | 'IMAP' | 'EXCHANGE' | 'ICLOUD' | 'YAHOO'
      feature_type: 'ai_remix' | 'ai_dictate' | 'voice_message' | 'sms' | 'calendar_event' | 'smart_compose'
    }
  }
}
